# Generated by Django 2.2.10 on 2021-01-12 07:36

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'project/apps/accounts/fixtures/superuser_fixture.json')


def unload_fixture(apps, schema_editor):
    """Brutally deleting all entries for this model..."""
    user_model = apps.get_model("auth", "User")
    user_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
